// Generated by CoffeeScript 1.6.3
(function() {
  var Server, config;

  config = require('config');

  Server = (function() {
    function Server() {}

    Server.prototype.logPrefix = "[app.server]:";

    Server.prototype.log = log;

    Server.prototype.router = function() {
      return this.app.get('/', function(req, res) {
        return res.render('layout');
      });
    };

    Server.prototype.use = function(app) {
      this.app = app;
      this.router();
      return this.log('initialized');
    };

    return Server;

  })();

  module.exports = new Server();

}).call(this);
