// Generated by CoffeeScript 1.6.3
(function() {
  var Server, config, helpers;

  helpers = require('../shared/helpers');

  config = require('config');

  Server = (function() {
    function Server() {}

    Server.prototype.logPrefix = '[app.server]:';

    Server.prototype.log = helpers.log;

    Server.prototype.handle404 = function(req, res, next) {
      res.status(404);
      return res.render('pages/404');
    };

    Server.prototype.router = function() {
      return this.app.get('/', function(req, res) {
        return res.render('layout');
      });
    };

    Server.prototype.use = function(app) {
      this.app = app;
      this.router();
      this.app.use(this.handle404);
      return this.log('initialized');
    };

    return Server;

  })();

  module.exports = new Server();

}).call(this);
